package cn.edu.sdu.sdudoc.sdudocdao.entity;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.addTime
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookAuthor
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private String bookauthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.dynasty
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private String dynasty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pulishedTime
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private Date pulishedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.totalArticle
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private String totalarticle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.uId
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.addTime
     *
     * @return the value of book.addTime
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.addTime
     *
     * @param addtime the value for book.addTime
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookAuthor
     *
     * @return the value of book.bookAuthor
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public String getBookauthor() {
        return bookauthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookAuthor
     *
     * @param bookauthor the value for book.bookAuthor
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setBookauthor(String bookauthor) {
        this.bookauthor = bookauthor == null ? null : bookauthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.dynasty
     *
     * @return the value of book.dynasty
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.dynasty
     *
     * @param dynasty the value for book.dynasty
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pulishedTime
     *
     * @return the value of book.pulishedTime
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public Date getPulishedtime() {
        return pulishedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pulishedTime
     *
     * @param pulishedtime the value for book.pulishedTime
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setPulishedtime(Date pulishedtime) {
        this.pulishedtime = pulishedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.totalArticle
     *
     * @return the value of book.totalArticle
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public String getTotalarticle() {
        return totalarticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.totalArticle
     *
     * @param totalarticle the value for book.totalArticle
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setTotalarticle(String totalarticle) {
        this.totalarticle = totalarticle == null ? null : totalarticle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.uId
     *
     * @return the value of book.uId
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.uId
     *
     * @param uid the value for book.uId
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}