package cn.edu.sdu.sdudoc.mapper;

import cn.edu.sdu.sdudoc.pojo.Book;
import java.util.Date;
import java.util.List;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    int deleteByPrimaryKey(Date addTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    Book selectByPrimaryKey(Date addTime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    int updateByPrimaryKey(Book record);
}