package cn.edu.sdu.sdudoc.mapper;

import cn.edu.sdu.sdudoc.pojo.Img;
import java.util.List;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    Img selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    List<Img> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    int updateByPrimaryKey(Img record);
}