package cn.edu.sdu.sdudocdoc.mapper;

import cn.edu.sdu.sdudocdoc.entity.Img;
import java.util.List;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sat Mar 27 21:56:49 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sat Mar 27 21:56:49 CST 2021
     */
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sat Mar 27 21:56:49 CST 2021
     */
    Img selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sat Mar 27 21:56:49 CST 2021
     */
    List<Img> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Sat Mar 27 21:56:49 CST 2021
     */
    int updateByPrimaryKey(Img record);
}