package cn.edu.sdu.sdudoc.sdudocdao.mapper;

import cn.edu.sdu.sdudoc.sdudocdao.entity.Book;
import java.util.Date;
import java.util.List;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    int deleteByPrimaryKey(Date addtime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    Book selectByPrimaryKey(Date addtime);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    List<Book> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    int updateByPrimaryKey(Book record);
}