package cn.edu.sdu.sdudoc.sdudocdao.mapper;

import cn.edu.sdu.sdudoc.sdudocdao.entity.Img;
import java.util.List;

public interface ImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    int insert(Img record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    Img selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    List<Img> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table img
     *
     * @mbggenerated Tue Mar 30 11:42:31 CST 2021
     */
    int updateByPrimaryKey(Img record);
}