package cn.edu.sdu.sdudoc.pojo;

import java.util.Date;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.addTime
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookAuthor
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private String bookAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.dynasty
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private String dynasty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.bookname
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private String bookname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.pulishedTime
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private Date pulishedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.totalArticle
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private String totalArticle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.uId
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private String uId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.addTime
     *
     * @return the value of book.addTime
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.addTime
     *
     * @param addTime the value for book.addTime
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookAuthor
     *
     * @return the value of book.bookAuthor
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookAuthor
     *
     * @param bookAuthor the value for book.bookAuthor
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.dynasty
     *
     * @return the value of book.dynasty
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.dynasty
     *
     * @param dynasty the value for book.dynasty
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.bookname
     *
     * @return the value of book.bookname
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public String getBookname() {
        return bookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.bookname
     *
     * @param bookname the value for book.bookname
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setBookname(String bookname) {
        this.bookname = bookname == null ? null : bookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.pulishedTime
     *
     * @return the value of book.pulishedTime
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public Date getPulishedTime() {
        return pulishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.pulishedTime
     *
     * @param pulishedTime the value for book.pulishedTime
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setPulishedTime(Date pulishedTime) {
        this.pulishedTime = pulishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.totalArticle
     *
     * @return the value of book.totalArticle
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public String getTotalArticle() {
        return totalArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.totalArticle
     *
     * @param totalArticle the value for book.totalArticle
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setTotalArticle(String totalArticle) {
        this.totalArticle = totalArticle == null ? null : totalArticle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.uId
     *
     * @return the value of book.uId
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.uId
     *
     * @param uId the value for book.uId
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }
}