package cn.edu.sdu.sdudoc.pojo;

public class Img {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.id
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column img.url
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.id
     *
     * @return the value of img.id
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.id
     *
     * @param id the value for img.id
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column img.url
     *
     * @return the value of img.url
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column img.url
     *
     * @param url the value for img.url
     *
     * @mbggenerated Mon Mar 29 22:30:42 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}